### ISSUE TITLE
Mispositioned popover

### ISSUE THREAD

**Issue by johnnysprinkles** [floating-ui/floating-ui#2035]
Seems to have something to do with the combination of flexbox, padding, and position:sticky. See repro at https://codesandbox.io/s/floating-ui-dom-template-forked-hexffu?file=/index.html

![Screen Shot 2022-12-15 at 10 27 40 AM](https://user-images.githubusercontent.com/32530010/207939035-82c31ceb-3bf8-4cc7-8ad1-708d2f112739.png)

This is the 1.0.10 version.

**Comment by atomiks** [comment]
Yeah that's not good 😕, if the offsetParent has a `padding` or `border` then the position is wrong. Caused by https://github.com/floating-ui/floating-ui/pull/2019 so it's not in `v1.0.9`. 

Seems the `border.offsetParent` test didn't catch it. This scale issue is proving problematic 😅

**Comment by atomiks** [comment]
I was wondering why I couldn't reproduce it locally, and it's because `box-sizing: border-box` is set on everything (this is usually the default with most stylesheets/CSS setups). 

So if you add that to your CSS, it'll fix the issue (you shouldn't have to though, this is an edge case that needs to be handled).

**Comment by atomiks** [comment]
`v1.0.12` will have both fixes (releasing soon) — I've had to fallback to the old technique because adding borders/padding is problematic if the scaled element has scrollbars. The fallback technique works in the vast majority of cases for scaled elements without `border-box`, and if it does not, adding that CSS property (which is widely recommended anyway) will use the new technique without the issues.

**Comment by johnnysprinkles** [comment]
Thanks for taking a look. Yeah, I don't agree with everything in e.g. [Josh Comeau's CSS reset](https://www.joshwcomeau.com/css/custom-css-reset/), but this does make an argument for #1 in there. I can confirm the position is much better with a global `box-sizing` set. I am still chasing down a separate position issue though that's present even with box-sizing border-box, I hope to have a repro case soon for 1.0.10.

**Comment by johnnysprinkles** [comment]
That other issue I mentioned, after a bunch of investigation it turns out to be this repro case:
https://codesandbox.io/s/floating-ui-dom-template-forked-h9m8m8?file=/src/styles.css

Which only repros if you have macOS scrollbars set to "Always."

The popover is misaligned by roughly 1 scrollbar width. The issue there is I wasn't giving the popover any default CSS-fed position so it was going at the end of the body and offscreen and causing a scrollbar.

This is covered in the documentation though where it says to use `top: 0; left: 0;`. Perhaps it should even be `top: -5000px; left: -5000px;` or something.

**Comment by johnnysprinkles** [comment]
Also, I got 1.0.12 and confirmed the original issue is fixed.

I'm using @floating-ui/dom with Svelte and SvelteKit, wrapped up as an action, and it works great.

**Comment by atomiks** [comment]
Popper always used top/left of `0` and there weren't any complaints afaik, but maybe there's a super edge case where it's not enough still.

**Comment by johannesmutter** [comment]
It seems this error is still happening.
If a parent element has `position: sticky` and `padding: 100px`, then the native popover will be offset the padding of the parent.

A temporary fix is to offset by the padding:

```javascript
function position_popover(event) {
    open = event.newState === 'open'
    if(!anchor){
      console.error("Popover: no anchor defined")
      return
    }

    // Bug fix for floating-ui: if a parent container is sticky and has padding, the popover will be offset by the padding
    const sticky_el = anchor.closest('.sticky');
    let offset_padding;
    if(sticky_el){
      offset_padding = get_padding(sticky_el);
    }    

    visibility = 'visible'; // prevents flickering
    let popover_el = event.target;
    // automatically update on ancestor/element resize or scroll, layoutshift, animation (default: false)
    autoUpdate(anchor, popover_el, ()=>{
      computePosition(anchor, popover_el, {
        placement,
        strategy: fixed_position ? 'fixed' : 'absolute',
      }).then(({x, y}) => {
        top = y + (offset?.y ?? offset ?? 0);
        left = x + (offset?.x ?? 0);
        if(offset_padding){
          top = top + offset_padding.top;
          left = left + offset_padding.left;
        }
      });
    });
  }
```

**Comment by atomiks** [comment]
@johannesmutter it's not happening with 1.5.3 in the repro sandbox provided still. If you have a valid reproduction, please make a new issue
