### ISSUE TITLE
[React/DOM] Hook name collision `(useFloating)` on previous webpack version

### ISSUE THREAD

**Issue by hpaul** [floating-ui/floating-ui#2110]
Firstly, thanks for your work on this project! 🙂 No one understand what it takes to position a floating div until he has to do it.

Today I had to use [patch-package](https://github.com/ds300/patch-package) to patch `@floating-ui/react@0.16.0` for the project I'm working on. Because it seems like on a production build, webpack would use `@floating-ui/react-dom` imports instead of `@floating-ui/react`,  the `useFloating` hook name is shared by both of them.

Webpack and adjacent plugins versions:
```
├─┬ babel-loader@8.2.5
│ └── webpack@4.46.0 deduped
├─┬ eslint-import-resolver-webpack@0.10.1
│ └── webpack@4.46.0 deduped
├─┬ hard-source-webpack-plugin@0.13.1
│ └── webpack@4.46.0 deduped
├─┬ postcss-loader@4.3.0
│ └── webpack@4.46.0 deduped
├─┬ terser-webpack-plugin@4.2.3
│ └── webpack@4.46.0 deduped
└─┬ webpack@4.46.0
  └─┬ terser-webpack-plugin@1.4.5
    └── webpack@4.46.0 deduped
```

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@floating-ui/react/src/index.d.ts b/node_modules/@floating-ui/react/src/index.d.ts
index 499cc0e..832d97e 100644
--- a/node_modules/@floating-ui/react/src/index.d.ts
+++ b/node_modules/@floating-ui/react/src/index.d.ts
@@ -1,3 +1,4 @@
+export * from '@floating-ui/react-dom';
 export { FloatingDelayGroup, useDelayGroup, useDelayGroupContext, } from './components/FloatingDelayGroup';
 export { FloatingFocusManager } from './components/FloatingFocusManager';
 export { FloatingOverlay } from './components/FloatingOverlay';
@@ -17,4 +18,3 @@ export { inner, useInnerOffset } from './inner';
 export { safePolygon } from './safePolygon';
 export { useFloating } from './useFloating';
 export { useInteractions } from './useInteractions';
-export * from '@floating-ui/react-dom';
```

At this moment I don't know if it's a bug from webpack or the names of the hooks should really be different, but I'm writing this here so anyone who bumps into this problem would have the response.

**Comment by atomiks** [comment]
Thanks for the report, the new sort imports plugin I added did that and I guess it can be a problem in this case.

[Fixed it here](https://github.com/floating-ui/floating-ui/commit/48370ecb9a83af42e39028831527abab099e255b), will be out in `v0.17.0`

**Comment by hpaul** [comment]
And there is another one related, but on parcel. https://github.com/parcel-bundler/parcel/issues/8652#issue-1459182813

Thank you @atomiks for the fast reply.

**Comment by atomiks** [comment]
Yeah Parcel was broken even with the export first as in the patch, but it's fixed in latest version.

**Comment by hpaul** [comment]
Seems like the issue is still happening. The production build still uses the `useFloating` from `@floating-ui/react-dom`.

I don't know what is the cause and why `dev` builds don't crash but seems like the `export * from '@floating-ui/react-dom'` does always expand after exports of current file.


```
/***/ "./node_modules/@floating-ui/react/dist/floating-ui.react.esm.js":
/*!***********************************************************************!*\
  !*** ./node_modules/@floating-ui/react/dist/floating-ui.react.esm.js ***!
  \***********************************************************************/
/*! exports provided: autoPlacement, detectOverflow, flip, hide, inline, limitShift, offset, shift, size, autoUpdate, computePosition, getOverflowAncestors, platform, arrow, FloatingDelayGroup, FloatingFocusManager, FloatingNode, FloatingOverlay, FloatingPortal, FloatingTree, inner, safePolygon, useClick, useDelayGroup, useDelayGroupContext, useDismiss, useFloating, useFloatingNodeId, useFloatingParentNodeId, useFloatingPortalNode, useFloatingTree, useFocus, useHover, useId, useInnerOffset, useInteractions, useListNavigation, useMergeRefs, useRole, useTransitionStatus, useTransitionStyles, useTypeahead */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "FloatingDelayGroup", function() { return FloatingDelayGroup; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "FloatingFocusManager", function() { return FloatingFocusManager; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "FloatingNode", function() { return FloatingNode; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "FloatingOverlay", function() { return FloatingOverlay; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "FloatingPortal", function() { return FloatingPortal; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "FloatingTree", function() { return FloatingTree; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "inner", function() { return inner; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "safePolygon", function() { return safePolygon; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "useClick", function() { return useClick; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "useDelayGroup", function() { return useDelayGroup; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "useDelayGroupContext", function() { return useDelayGroupContext; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "useDismiss", function() { return useDismiss; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "useFloating", function() { return useFloating; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "useFloatingNodeId", function() { return useFloatingNodeId; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "useFloatingParentNodeId", function() { return useFloatingParentNodeId; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "useFloatingPortalNode", function() { return useFloatingPortalNode; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "useFloatingTree", function() { return useFloatingTree; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "useFocus", function() { return useFocus; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "useHover", function() { return useHover; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "useId", function() { return useId; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "useInnerOffset", function() { return useInnerOffset; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "useInteractions", function() { return useInteractions; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "useListNavigation", function() { return useListNavigation; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "useMergeRefs", function() { return useMergeRefs; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "useRole", function() { return useRole; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "useTransitionStatus", function() { return useTransitionStatus; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "useTransitionStyles", function() { return useTransitionStyles; });
/* harmony export (binding) */ __webpack_require__.d(__webpack_exports__, "useTypeahead", function() { return useTypeahead; });
/* harmony import */ var _floating_ui_react_dom__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! @floating-ui/react-dom */ "./node_modules/@floating-ui/react-dom/dist/floating-ui.react-dom.esm.js");
/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "autoPlacement", function() { return _floating_ui_react_dom__WEBPACK_IMPORTED_MODULE_0__["autoPlacement"]; });

/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "detectOverflow", function() { return _floating_ui_react_dom__WEBPACK_IMPORTED_MODULE_0__["detectOverflow"]; });

/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "flip", function() { return _floating_ui_react_dom__WEBPACK_IMPORTED_MODULE_0__["flip"]; });

/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "hide", function() { return _floating_ui_react_dom__WEBPACK_IMPORTED_MODULE_0__["hide"]; });

/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "inline", function() { return _floating_ui_react_dom__WEBPACK_IMPORTED_MODULE_0__["inline"]; });

/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "limitShift", function() { return _floating_ui_react_dom__WEBPACK_IMPORTED_MODULE_0__["limitShift"]; });

/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "offset", function() { return _floating_ui_react_dom__WEBPACK_IMPORTED_MODULE_0__["offset"]; });

/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "shift", function() { return _floating_ui_react_dom__WEBPACK_IMPORTED_MODULE_0__["shift"]; });

/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "size", function() { return _floating_ui_react_dom__WEBPACK_IMPORTED_MODULE_0__["size"]; });

/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "autoUpdate", function() { return _floating_ui_react_dom__WEBPACK_IMPORTED_MODULE_0__["autoUpdate"]; });

/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "computePosition", function() { return _floating_ui_react_dom__WEBPACK_IMPORTED_MODULE_0__["computePosition"]; });

/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "getOverflowAncestors", function() { return _floating_ui_react_dom__WEBPACK_IMPORTED_MODULE_0__["getOverflowAncestors"]; });

/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "platform", function() { return _floating_ui_react_dom__WEBPACK_IMPORTED_MODULE_0__["platform"]; });

/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "arrow", function() { return _floating_ui_react_dom__WEBPACK_IMPORTED_MODULE_0__["arrow"]; });

/* harmony reexport (safe) */ __webpack_require__.d(__webpack_exports__, "useFloating", function() { return _floating_ui_react_dom__WEBPACK_IMPORTED_MODULE_0__["useFloating"]; });

/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! react */ "./node_modules/react/index.js");
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_1___default = /*#__PURE__*/__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_1__);
/* harmony import */ var aria_hidden__WEBPACK_IMPORTED_MODULE_2__ = __webpack_require__(/*! aria-hidden */ "./node_modules/aria-hidden/dist/es2015/index.js");
/* harmony import */ var tabbable__WEBPACK_IMPORTED_MODULE_3__ = __webpack_require__(/*! tabbable */ "./node_modules/tabbable/dist/index.esm.js");
/* harmony import */ var react_dom__WEBPACK_IMPORTED_MODULE_4__ = __webpack_require__(/*! react-dom */ "./node_modules/react-dom/index.js");
/* harmony import */ var react_dom__WEBPACK_IMPORTED_MODULE_4___default = /*#__PURE__*/__webpack_require__.n(react_dom__WEBPACK_IMPORTED_MODULE_4__);
```

**Comment by atomiks** [comment]
`v0.17.0` uses the same order as your patch, I guess it may be necessary to individually export the modules to avoid the collision instead.

**Comment by hpaul** [comment]
Yes, it made sense, and the PR for production worked. But as another PR was merged, the same error showed up.
And today my thought (it should had been the first one) was to check how the library is compiled on a dev environment and it crossed me that the exports from `../react-dom` were the latest ones.

I really don't know what else could be done beside importing and exporting manually all fns from `@floating-ui/react-dom`

**Comment by hpaul** [comment]
Thank you @atomiks!! I was going to push a PR nexts days, as we had patched our app with right exports, after trying a few different angles on webpack. 

But looks like are eager when it comes to bugs on the library 👌. Thank you again!!

**Comment by atomiks** [comment]
@hpaul nice, can you confirm the change I made works correctly?

**Comment by hpaul** [comment]
I had compiled it locally and have used it in the bundle and I can confirm it's working.

Waiting for the next version on `npm`. :+1: 

Thanks again!

**Comment by atomiks** [comment]
This is now released in`v0.18.0`
